
## Exercise 1: NumPy array Indexing/Slicing

1.1) Neste exercício, vamos utilizar o conjunto de dados da íris. Carregue
o ficheiro “iris.csv” utilizando o método apropriado para este tipo de ficheiro
(utilize as novas funções do pacote).



In [1]:
import os
from si.io.csv_file import read_csv

# Usando o caminho correto no Windows
file_path = r"C:\Users\diana\OneDrive\Ambiente de Trabalho\Sist. Inteligentes\23 set\session2-notebooks\iris.csv"
# Carregando o dataset iris
dataset = read_csv(file_path, sep=',', features=True, label=True)

# Verificar se o dataset foi carregado corretamente
print(dataset.X)
print(dataset.y)


[[1.00e+00 5.10e+00 3.50e+00 1.40e+00 2.00e-01]
 [2.00e+00 4.90e+00 3.00e+00 1.40e+00 2.00e-01]
 [3.00e+00 4.70e+00 3.20e+00 1.30e+00 2.00e-01]
 [4.00e+00 4.60e+00 3.10e+00 1.50e+00 2.00e-01]
 [5.00e+00 5.00e+00 3.60e+00 1.40e+00 2.00e-01]
 [6.00e+00 5.40e+00 3.90e+00 1.70e+00 4.00e-01]
 [7.00e+00 4.60e+00 3.40e+00 1.40e+00 3.00e-01]
 [8.00e+00 5.00e+00 3.40e+00 1.50e+00 2.00e-01]
 [9.00e+00 4.40e+00 2.90e+00 1.40e+00 2.00e-01]
 [1.00e+01 4.90e+00 3.10e+00 1.50e+00 1.00e-01]
 [1.10e+01 5.40e+00 3.70e+00 1.50e+00 2.00e-01]
 [1.20e+01 4.80e+00 3.40e+00 1.60e+00 2.00e-01]
 [1.30e+01 4.80e+00 3.00e+00 1.40e+00 1.00e-01]
 [1.40e+01 4.30e+00 3.00e+00 1.10e+00 1.00e-01]
 [1.50e+01 5.80e+00 4.00e+00 1.20e+00 2.00e-01]
 [1.60e+01 5.70e+00 4.40e+00 1.50e+00 4.00e-01]
 [1.70e+01 5.40e+00 3.90e+00 1.30e+00 4.00e-01]
 [1.80e+01 5.10e+00 3.50e+00 1.40e+00 3.00e-01]
 [1.90e+01 5.70e+00 3.80e+00 1.70e+00 3.00e-01]
 [2.00e+01 5.10e+00 3.80e+00 1.50e+00 3.00e-01]
 [2.10e+01 5.40e+00 3.40e+00 1.70e+00 2.

1.2) Selecione a penúltima variável independente. Qual é a dimensão da matriz resultante?

In [2]:
# Selecionando a penúltima variável (penúltima coluna)
# dataset.X : features 
penultimate_feature = dataset.X[:, -2]

# Dimensão do array resultante
print("Dimensão da penúltima variável independente:", penultimate_feature.shape)


Dimensão da penúltima variável independente: (150,)


1.3) Selecione as últimas 10 amostras do conjunto de dados da íris. 
Qual é a média das últimas 10 amostras para cada variável independente/caraterística?


In [3]:
# Selecionando as últimas 10 amostras
last_10_samples = dataset.X[-10:, :]

# Calculando a média para cada variável independente
mean_last_10 = last_10_samples.mean(axis=0)

print("Média das últimas 10 amostras por variável independente:", mean_last_10)


Média das últimas 10 amostras por variável independente: [145.5    6.45   3.03   5.33   2.17]


1.4) Selecione todas as amostras do conjunto de dados com valores menores ou iguais a 6 para todas 
as variáveis independentes/caraterísticas. Quantas amostras obtém?

In [4]:
import numpy as np

# Selecionar amostras onde todas as variáveis são <= 6
samples_less_equal_6 = dataset.X[np.all(dataset.X <= 6, axis=1)]

# Quantidade de amostras selecionadas
print("Número de amostras com todas as variáveis <= 6:", samples_less_equal_6.shape[0])



Número de amostras com todas as variáveis <= 6: 6


1.5) Selecione todas as amostras com uma classe/rótulo diferente de diferente de “Iris-setosa”.
 Quantas amostras obtém?

In [5]:

# Selecionar amostras com classe diferente de 'Iris-setosa'
samples_not_setosa = dataset.X[dataset.y != 'Iris-setosa']

# Quantidade de amostras selecionadas
print("Número de amostras com classe diferente de 'Iris-setosa':", samples_not_setosa.shape[0])


Número de amostras com classe diferente de 'Iris-setosa': 150
